version: "3.9"
services:
  rss:
    build: .
    ports:
      - "80:80"
    environment:
      RSS_DB_HOST: ${RSS_DB_HOST:-postgres}
      RSS_DB_PORT: ${RSS_DB_PORT:-5432}
      RSS_DB_NAME: ${POSTGRES_DB:-postgres}
      RSS_DB_USER: ${POSTGRES_USER:-postgres}
      RSS_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      RSS_DB_ENABLE_SSL: ${RSS_DB_ENABLE_SSL:-false}

      RSS_SERVER_PORT: ${RSS_SERVER_PORT:-80}
      RSS_SERVER_READ_TIMEOUT: ${RSS_SERVER_READ_TIMEOUT:-300ms}
      RSS_SERVER_WRITE_TIMEOUT: ${RSS_SERVER_WRITE_TIMEOUT:-5000ms}

      RSS_CACHER_WORKERS_COUNT: ${RSS_CACHER_WORKERS_COUNT:-4}
      RSS_CACHER_PULL_PERIOD: ${RSS_CACHER_PULL_PERIOD:-500ms}
      RSS_CACHER_BATCH_SIZE: ${RSS_CACHER_BATCH_SIZE:-100}

      RSS_GOOGLE_AUTH_CLIENT_ID: ${RSS_GOOGLE_AUTH_CLIENT_ID}
      RSS_GOOGLE_AUTH_CLIENT_SECRET: ${RSS_GOOGLE_AUTH_CLIENT_SECRET}
      RSS_GOOGLE_AUTH_REDIRECT_URL: ${RSS_GOOGLE_AUTH_REDIRECT_URL:-http://localhost/}
  postgres:
    image: "postgres:latest"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5445:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}